-- =============================================================================
-- REVERSIBLE TABLES - REMOVED
-- =============================================================================
-- This file previously contained definitions for *_reversible tables:
--   - hafd.blocks_reversible
--   - hafd.transactions_reversible
--   - hafd.transactions_multisig_reversible
--   - hafd.operations_reversible
--   - hafd.accounts_reversible
--   - hafd.account_operations_reversible
--   - hafd.applied_hardforks_reversible
--
-- These tables have been removed as part of the unified block_id refactoring.
-- All data (both irreversible and reversible) is now stored in the main tables
-- (hafd.blocks, hafd.operations, etc.) with block_id encoding (block_num, fork_id).
--
-- See: refactoring.md for design details
-- =============================================================================
