-- Tests for hafd.operation_id(), hafd.operation_id_to_block_num(), hafd.operation_id_to_pos()
-- have been removed because these functions no longer exist.
-- Operations now use (block_num, op_pos_in_block) composite PK directly.
